<a href="https://www.kaggle.com/chandanarprasad/best-cities-and-countries-for-startup?scriptVersionId=84586793" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/best-cities-and-countries-for-startups-in-2021/Best Countries for Startups.csv
/kaggle/input/best-cities-and-countries-for-startups-in-2021/Best Cities for Startups.csv

In [2]:
import pandas as pd

In [3]:
df_country = pd.read_csv('../input/best-cities-and-countries-for-startups-in-2021/Best Countries for Startups.csv')
df_city = pd.read_csv('../input/best-cities-and-countries-for-startups-in-2021/Best Cities for Startups.csv')

In [4]:
#Strip trailing whitespaces and replace space with underscore

df_country.columns = df_country.columns.str.strip()
df_country.columns = df_country.columns.str.replace(' ','_')

df_city.columns = df_city.columns.str.strip()
df_city.columns = df_city.columns.str.replace(' ','_')

In [5]:
df_country.head()

,ranking,change_in_position_from_2020,country,total_score,quantity_score,quality_score,business_score,change_in_position_sign
0,1.0,0,United States,124.420,19.45,101.17,3.80,NaN
1,2.0,0,United Kingdom,28.719,8.16,16.86,3.70,NaN
2,3.0,0,Israel,27.741,5.48,19.14,3.13,NaN
3,4.0,0,Canada,19.876,6.58,9.75,3.55,NaN
4,5.0,0,Germany,17.053,3.64,9.93,3.49,NaN

In [6]:
df_city.head(20)

,position,change_in_position_from_2020,city,country,total_score,quatity_score,quality_score,business_score,sign_of_change_in_position
0,1,0,San Francisco Bay,United States,328.966,29.14,296.02,3.80,NaN
1,2,0,New York,United States,110.777,11.43,95.55,3.80,NaN
2,3,3,Beijing,China,66.049,5.01,58.61,2.43,+
3,4,1,Los Angeles Area,United States,58.441,11.23,43.41,3.80,+
4,5,2,London,United Kingdom,56.913,15.77,37.44,3.70,-
5,6,2,Boston Area,United States,49.835,5.50,40.53,3.80,-
6,7,3,Shanghai,China,42.162,3.57,36.17,2.43,+
7,8,1,Tel Aviv Area,Israel,27.084,4.04,19.92,3.13,-
8,9,0,Moscow,Russia,25.401,7.37,15.64,2.39,NaN
9,10,4,Bangalore,India,25.367,5.04,17.95,2.38,+
10,11,1,Paris,France,25.297,5.27,16.62,3.41,+
11,12,1,Seattle,United States,24.329,3.49,17.04,3.80,-
12,13,5,Berlin,Germany,23.872,4.03,16.35,3.49,-
13,14,1,New Delhi,India,22.379,5.88,13.90,2.61,+
14,15,1,Tokyo,Japan,21.792,2.50,16.00,3.30,+
15,16,6,Mumbai,India,19.414,3.27,13.54,2.61,+
16,17,4,Chicago,United States,19.121,4.37,10.95,3.80,-
17,18,1,Austin,United States,18.598,3.20,11.60,3.80,-
18,19,11,Washington DC Area,United States,18.064,3.47,10.79,3.80,+
19,20,2,Sao Paulo,Brazil,17.642,2.63,12.72,2.29,-

In [7]:
print(df_country.isna().any().sum(),df_city.isna().any().sum())

8 1

In [8]:
df_country[['country','ranking','total_score']].sort_values(by = 'total_score',ascending=False).head(10)

          country  ranking  total_score
0   United States      1.0      124.420
1  United Kingdom      2.0       28.719
2          Israel      3.0       27.741
3          Canada      4.0       19.876
4         Germany      5.0       17.053
5          Sweden      6.0       15.423
6           China      7.0       15.128
7     Switzerland      8.0       14.943
8       Australia      9.0       13.835
9       Singapore     10.0       13.745

In [9]:
df_country.tail(20)

,ranking,change_in_position_from_2020,country,total_score,quantity_score,quality_score,business_score,change_in_position_sign
81,82.0,5,Tunisia,0.395,0.14,0.07,0.19,-
82,83.0,4,Panama,0.355,0.09,0.08,0.19,+
83,84.0,0,Qatar,0.352,0.10,0.09,0.17,NaN
84,85.0,12,Bosnia and Herzegovina,0.351,0.10,0.08,0.17,-
85,86.0,15,Ecuador,0.330,0.12,0.06,0.15,-
86,87.0,4,Cape Verde,0.319,0.15,0.05,0.11,+
87,88.0,5,Mongolia,0.314,0.10,0.05,0.16,+
88,89.0,19,Azerbaijan,0.309,0.09,0.05,0.17,-
89,90.0,2,Kuwait,0.259,0.04,0.09,0.12,+
90,91.0,11,Paraguay,0.253,0.07,0.06,0.12,-
91,92.0,7,Sri Lanka,0.245,0.09,0.04,0.12,+
92,93.0,5,Bangladesh,0.241,0.08,0.08,0.09,+
93,94.0,1,Somalia,0.224,0.14,0.05,0.04,+
94,95.0,12,Morocco,0.220,0.06,0.05,0.12,-
95,96.0,18,Dominican Republic,0.197,0.06,0.04,0.09,-
96,97.0,8,Uganda,0.180,0.07,0.04,0.07,-
97,98.0,2,Nepal,0.172,0.06,0.04,0.08,+
98,99.0,new entry,Namibia,0.165,0.04,0.05,0.07,NaN
99,100.0,new entry,Ethiopia,0.162,0.07,0.06,0.03,NaN
100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df_city.tail(20)

,position,change_in_position_from_2020,city,country,total_score,quatity_score,quality_score,business_score,sign_of_change_in_position
980,981,14,Kano,Nigeria,0.076,0.01,0.02,0.04,+
981,982,new,Buea,Cameroon,0.076,0.02,0.02,0.04,NaN
982,983,16,Maputo,Mozambique,0.074,0.02,0.02,0.03,-
983,984,16,Algiers,Algeria,0.071,0.01,0.03,0.03,-
984,985,7,Kabul,Afghanistan,0.070,0.02,0.02,0.03,+
985,986,new,Yaounde,Cameroon,0.069,0.01,0.02,0.03,NaN
986,987,new,Saint Peter Port,Guernsey,0.069,0.05,0.02,0.00,NaN
987,988,new,Jhelum,Pakistan,0.068,0.01,0.02,0.04,NaN
988,989,new,Port-au-Prince,Haiti,0.068,0.03,0.02,0.03,NaN
989,990,new,Multan,Pakistan,0.067,0.01,0.02,0.04,NaN
990,991,8,Kinshasa,Democratic Republic of the Congo,0.066,0.02,0.03,0.02,+
991,992,new,Douglas,Isle of Man,0.064,0.01,0.05,0.00,NaN
992,993,new,Chattogram,Bangladesh,0.064,0.01,0.02,0.03,NaN
993,994,3,Bridgetown,Barbados,0.062,0.01,0.02,0.03,+
994,995,new,Cotonou,Benin,0.061,0.01,0.02,0.03,NaN
995,996,26,Ouagadougou,Burkina Faso,0.060,0.02,0.02,0.02,-
996,997,new,Baghdad,Iraq,0.058,0.01,0.02,0.03,NaN
997,998,13,Mbabane,Swaziland,0.057,0.01,0.02,0.03,-
998,999,new,Conakry,Guinea,0.047,0.01,0.02,0.02,NaN
999,1000,new,Sanaa,Yemen,0.037,0.01,0.02,0.01,NaN